import { Router } from 'express';
import { getDb } from '../db.js';
import {
  getVapidKeys,
  deliverPush,
  deliverWebhook,
  enabledChannels,
  recordTestNotification,
} from '../notifications.js';
import { webhookFormatDocs } from '../webhookFormats.js';

const router = Router();

const MAX_LIMIT = 100;
const DEFAULT_LIMIT = 30;

function formatNotification(row) {
  return {
    id: row.id,
    kind: row.kind,
    title: row.title,
    body: row.body,
    link: row.link,
    created_at: row.created_at,
    read: row.read_at != null,
  };
}

// Only rows written while the in-app centre was an enabled channel are part of
// the feed. Everything else is still stored - that is what dedupes delivery -
// but a webhook-only profile has not asked to see it here.
router.get('/', (req, res) => {
  const db = getDb();
  const limit = Math.min(MAX_LIMIT, Math.max(1, Number(req.query.limit) || DEFAULT_LIMIT));
  const rows = db.prepare(`
    SELECT * FROM notifications
    WHERE profile_id = ? AND inapp = 1
    ORDER BY created_at DESC, id DESC
    LIMIT ?
  `).all(req.profileId, limit);

  const unread = db.prepare(
    'SELECT COUNT(*) AS c FROM notifications WHERE profile_id = ? AND inapp = 1 AND read_at IS NULL'
  ).get(req.profileId).c;

  const channels = enabledChannels(req.profileId);
  res.json({
    notifications: rows.map(formatNotification),
    unread_count: unread,
    // Lets the client hide the bell entirely rather than showing one that can
    // never fill up.
    inapp_enabled: channels.includes('inapp'),
    // Carried here so push reconciliation can happen at profile scope, on the
    // poll this client already makes, instead of waiting for a visit to
    // Settings.
    push_enabled: channels.includes('push'),
  });
});

router.post('/read', (req, res) => {
  const info = getDb().prepare(
    "UPDATE notifications SET read_at = datetime('now') WHERE profile_id = ? AND inapp = 1 AND read_at IS NULL"
  ).run(req.profileId);
  res.json({ marked: info.changes });
});

router.post('/:id/read', (req, res) => {
  const id = Number(req.params.id);
  if (!Number.isInteger(id)) return res.status(400).json({ error: 'Invalid notification id' });

  // profile_id in the WHERE clause is the authorization check: another
  // household member's notification simply does not match.
  const info = getDb().prepare(
    "UPDATE notifications SET read_at = datetime('now') WHERE id = ? AND profile_id = ? AND read_at IS NULL"
  ).run(id, req.profileId);

  const exists = getDb()
    .prepare('SELECT 1 FROM notifications WHERE id = ? AND profile_id = ?')
    .get(id, req.profileId);
  if (!exists) return res.status(404).json({ error: 'Notification not found' });

  res.json({ marked: info.changes });
});

router.delete('/', (req, res) => {
  const info = getDb()
    .prepare('DELETE FROM notifications WHERE profile_id = ?')
    .run(req.profileId);
  res.json({ deleted: info.changes });
});

// Powers the in-app webhook documentation. The examples are generated by the
// same builder that composes real deliveries, so the docs cannot drift from
// what this instance actually sends - including whether links are absolute,
// which depends on APP_ORIGIN being set.
router.get('/webhook-formats', (req, res) => {
  res.json({
    formats: webhookFormatDocs({ appOrigin: process.env.APP_ORIGIN || null }),
    app_origin: process.env.APP_ORIGIN || null,
  });
});

// The browser needs the application server's public key to subscribe. Safe to
// hand out: it is public by definition, and generating it here means a fresh
// install has working push without any operator setup.
router.get('/vapid-key', (req, res) => {
  try {
    res.json({ public_key: getVapidKeys().publicKey });
  } catch (err) {
    console.error('VAPID key generation failed:', err);
    res.status(500).json({ error: 'Could not generate push keys' });
  }
});

router.post('/subscribe', (req, res) => {
  const { endpoint, keys } = req.body || {};
  if (typeof endpoint !== 'string' || !endpoint.startsWith('https://')) {
    return res.status(400).json({ error: 'A push subscription endpoint is required' });
  }
  if (!keys || typeof keys.p256dh !== 'string' || typeof keys.auth !== 'string') {
    return res.status(400).json({ error: 'Subscription keys are missing' });
  }

  // Keyed on (endpoint, profile_id): a shared browser can hold a subscription
  // for each household member at once. Re-subscribing the same pair refreshes
  // it in place instead of duplicating, and never disturbs another profile's.
  getDb().prepare(`
    INSERT INTO push_subscriptions (profile_id, endpoint, p256dh, auth, user_agent)
    VALUES (?, ?, ?, ?, ?)
    ON CONFLICT(endpoint, profile_id) DO UPDATE SET
      p256dh = excluded.p256dh,
      auth = excluded.auth,
      user_agent = excluded.user_agent,
      failure_count = 0
  `).run(req.profileId, endpoint, keys.p256dh, keys.auth, req.get('user-agent') || null);

  res.json({ subscribed: true });
});

// Drops only the calling profile's claim on this browser. `remaining` tells the
// client whether any other profile still uses the endpoint: revoking the
// browser-side PushSubscription while another profile depends on it would
// break push for them too, which is exactly what the old code did.
router.post('/unsubscribe', (req, res) => {
  const { endpoint } = req.body || {};
  if (typeof endpoint !== 'string') {
    return res.status(400).json({ error: 'A push subscription endpoint is required' });
  }
  const db = getDb();
  const info = db
    .prepare('DELETE FROM push_subscriptions WHERE endpoint = ? AND profile_id = ?')
    .run(endpoint, req.profileId);
  const remaining = db
    .prepare('SELECT COUNT(*) AS c FROM push_subscriptions WHERE endpoint = ?')
    .get(endpoint).c;

  res.json({ unsubscribed: info.changes > 0, remaining });
});

// Round-trips a real notification through every enabled channel so the Settings
// page can prove the wiring.
//
// The in-app arm writes an actual row rather than asserting one was shown:
// proving the bell and feed work is the whole point, and there is no way to do
// that without something to read back. Each test gets a unique dedupe key so
// pressing the button twice produces two.
router.post('/test', async (req, res) => {
  const channels = enabledChannels(req.profileId);
  // Records the row without fanning out. notify() delivers fire-and-forget,
  // which would both double-send and hide whether delivery actually worked -
  // and reporting that honestly is the point of this endpoint.
  const notification = recordTestNotification(req.profileId);

  // One entry per enabled channel, each saying whether it actually worked.
  // "Enabled" is not "delivered": an empty webhook URL, an HTTP error, or a
  // profile with no push subscription all fail while the channel is on, and a
  // test that reports success anyway is worse than no test at all.
  const results = [];

  if (channels.includes('inapp')) {
    // Reports on the row that was actually written, so a failure to store
    // cannot be reported as a success.
    results.push(notification.id
      ? { channel: 'inapp', ok: true, detail: 'Added to the notification centre' }
      : { channel: 'inapp', ok: false, detail: 'Could not store the notification' });
  }

  if (channels.includes('push')) {
    try {
      const { sent, pruned } = await deliverPush(req.profileId, notification);
      results.push(sent > 0
        ? { channel: 'push', ok: true, detail: `Sent to ${sent} device${sent === 1 ? '' : 's'}` }
        : {
            channel: 'push',
            ok: false,
            detail: pruned > 0
              ? 'The subscription for this device has expired - turn push off and on again'
              : 'No push subscription for this profile - turn push off and on again in this browser',
          });
    } catch (err) {
      results.push({ channel: 'push', ok: false, detail: err?.message || 'Push delivery failed' });
    }
  }

  if (channels.includes('webhook')) {
    try {
      const outcome = await deliverWebhook(req.profileId, notification);
      results.push(outcome.delivered
        ? { channel: 'webhook', ok: true, detail: `Target responded ${outcome.status}` }
        : {
            channel: 'webhook',
            ok: false,
            detail: outcome.status
              ? `Target responded ${outcome.status}`
              : 'No webhook URL set',
          });
    } catch (err) {
      results.push({
        channel: 'webhook',
        ok: false,
        // fetch rejections ("fetch failed") say nothing useful on their own.
        detail: err?.name === 'TimeoutError'
          ? 'Timed out after 5s'
          : `Could not reach the webhook URL (${err?.message || 'request failed'})`,
      });
    }
  }

  res.json({ channels, results, ok: results.length > 0 && results.every(entry => entry.ok) });
});

export default router;
