// Static UI copy for the webhook formats: labels, what each one works with,
// and what its URL looks like.
//
// This deliberately lives on the client. The byte-exact request example is
// still generated by the server (from the same function that composes real
// deliveries, so it cannot drift), but guidance must not depend on that fetch
// succeeding - an older server process, or the demo build with no server at
// all, would otherwise leave the format selector showing the wrong URL hint
// and no documentation whatsoever.
//
// The ids must stay in step with WEBHOOK_FORMATS in
// server/src/webhookFormats.js; a test asserts it.
export const WEBHOOK_FORMATS = [
  {
    id: 'json',
    label: 'ErgDash JSON',
    targets: 'Gotify, Home Assistant, custom scripts',
    hint: 'ErgDash\'s own shape, with the extra fields a script might want. Gotify reads title and message directly.',
    urlHint: 'https://gotify.example.com/message?token=YOUR_TOKEN',
  },
  {
    id: 'ntfy',
    label: 'ntfy',
    targets: 'ntfy.sh or a self-hosted ntfy',
    hint: 'Posts the message as the body with the title in an X-Title header, which is how ntfy expects it. Point the URL at your topic.',
    urlHint: 'https://ntfy.sh/your-topic',
  },
  {
    id: 'discord',
    label: 'Discord',
    targets: 'Discord channel webhook',
    hint: 'The webhook URL is all Discord needs - it identifies the channel and authorises the post. Create one under Channel Settings → Integrations → Webhooks.',
    urlHint: 'https://discord.com/api/webhooks/ID/TOKEN',
  },
  {
    id: 'slack',
    label: 'Slack / Mattermost',
    targets: 'Slack, Mattermost, Google Chat',
    hint: 'The incoming-webhook URL encodes the destination channel, so no extra configuration is needed. Mattermost and Google Chat accept the same shape.',
    urlHint: 'https://hooks.slack.com/services/T000/B000/XXXX',
  },
];

export function webhookFormat(id) {
  return WEBHOOK_FORMATS.find(format => format.id === id) || WEBHOOK_FORMATS[0];
}
