// Webhook payload shapes, one per target service.
//
// There is no universal webhook format. Sending our own JSON everywhere looks
// right until you try it: ntfy renders a JSON body as the literal message text
// (the body IS the message when you POST to a topic URL), and Discord ignores
// anything that is not `content`. So the shape is chosen explicitly, and this
// module is the only place that knows the difference.
//
// buildWebhookRequest() is also what generates the examples shown in Settings,
// so the in-app documentation cannot drift from what actually goes out.

export const WEBHOOK_FORMATS = ['json', 'ntfy', 'discord', 'slack'];

// ntfy shows these as an icon next to the message.
const NTFY_TAGS = {
  plan_reminder: 'calendar',
  workout_synced: 'rowboat',
  new_pb: 'trophy',
  missed_session: 'warning',
  streak_risk: 'fire',
};

// One line of plain text: "<title> — <body>", used by the formats that have a
// single message field rather than separate title and body.
function flatten(notification, separator = ' — ') {
  return [notification.title, notification.body].filter(Boolean).join(separator);
}

// An absolute link for services that make notifications clickable. Only
// possible when the operator has told ErgDash its public origin; app-relative
// paths are useless to an external service, so they are simply omitted.
function absoluteLink(notification, appOrigin) {
  if (!notification.link || !appOrigin) return null;
  try {
    return new URL(notification.link, appOrigin).href;
  } catch {
    return null;
  }
}

// Returns { headers, body } ready to hand to fetch(). Body is always a string.
export function buildWebhookRequest(format, notification, { appOrigin = null } = {}) {
  const link = absoluteLink(notification, appOrigin);

  if (format === 'ntfy') {
    // Publishing to https://ntfy.sh/<topic>: the raw body is the message and
    // everything else travels as X- headers. Header values must be latin-1, so
    // the title is stripped of anything outside it (our em dash, mostly).
    const headers = {
      'Content-Type': 'text/plain; charset=utf-8',
      'X-Title': asciiSafe(notification.title),
      'X-Tags': NTFY_TAGS[notification.kind] || 'rowboat',
    };
    if (link) headers['X-Click'] = link;
    return { headers, body: notification.body || notification.title };
  }

  if (format === 'discord') {
    // Discord rejects anything without `content` (or embeds), and caps it at
    // 2000 characters.
    const content = `**${notification.title}**${notification.body ? `\n${notification.body}` : ''}`;
    return {
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        content: (link ? `${content}\n${link}` : content).slice(0, 2000),
      }),
    };
  }

  if (format === 'slack') {
    // Slack's incoming-webhook shape, which Mattermost and Google Chat also
    // accept.
    const text = `*${notification.title}*${notification.body ? `\n${notification.body}` : ''}`;
    return {
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text: link ? `${text}\n${link}` : text }),
    };
  }

  // 'json': ErgDash's own shape. Gotify reads title/message directly, and it is
  // the one to target from a script or Home Assistant, where the extra fields
  // (kind, link) are worth having.
  return {
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      title: notification.title,
      message: notification.body,
      kind: notification.kind,
      link: notification.link,
      url: link,
      created_at: notification.created_at,
    }),
  };
}

// HTTP header values are latin-1; anything outside it would throw on send.
function asciiSafe(value) {
  return String(value ?? '').replace(/[^\x20-\x7E]/g, '-');
}

// Shown in Settings so the format selector explains itself. `sample` is
// generated by the builder above, so it is literally what would be sent.
const SAMPLE_NOTIFICATION = {
  kind: 'plan_reminder',
  title: "Today's session: 8 km",
  body: '4x2k / 5min rest',
  link: '/plan',
  created_at: '2026-07-26 07:00:00',
};

export const WEBHOOK_FORMAT_DOCS = [
  {
    id: 'json',
    label: 'ErgDash JSON',
    targets: 'Gotify, Home Assistant, custom scripts',
    hint: 'ErgDash\'s own shape, with the extra fields a script might want. Gotify reads title and message directly.',
    urlHint: 'https://gotify.example.com/message?token=YOUR_TOKEN',
  },
  {
    id: 'ntfy',
    label: 'ntfy',
    targets: 'ntfy.sh or a self-hosted ntfy',
    hint: 'Posts the message as the body with the title in an X-Title header, which is how ntfy expects it. Point the URL at your topic.',
    urlHint: 'https://ntfy.sh/your-topic',
  },
  {
    id: 'discord',
    label: 'Discord',
    targets: 'Discord channel webhook',
    hint: 'Discord only renders a "content" field. Create the webhook under Channel Settings → Integrations.',
    urlHint: 'https://discord.com/api/webhooks/ID/TOKEN',
  },
  {
    id: 'slack',
    label: 'Slack',
    targets: 'Slack, Mattermost, Google Chat',
    hint: 'The standard incoming-webhook "text" field, which Mattermost and Google Chat accept too.',
    urlHint: 'https://hooks.slack.com/services/T000/B000/XXXX',
  },
];

// appOrigin is passed in so the examples show the clickable-link behaviour
// exactly as this instance is configured.
export function webhookFormatDocs({ appOrigin = null } = {}) {
  return WEBHOOK_FORMAT_DOCS.map(doc => {
    const { headers, body } = buildWebhookRequest(doc.id, SAMPLE_NOTIFICATION, { appOrigin });
    return { ...doc, sample: { method: 'POST', headers, body } };
  });
}
